timeout: 25

wallpaper: boot():/boot/wallpaper.jpg
wallpaper_style: stretched

/astralisos
    protocol: limine
    path: boot():/boot/astralisos
    module_path: boot():/boot/astralisos
    module_path: boot():/boot/initrd.tar
    