#pragma once

#include <stdint.h>
#include <stdbool.h>

typedef enum key_action_t: bool
{
    KEY_ACTION_PRESS,
    KEY_ACTION_RELEASE,
} key_action_t;

typedef enum kbd_key_t
{
    KEY_NONE,
    KEY_ESC,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_0,
    KEY_MINUS,
    KEY_EQUALS,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_Q,
    KEY_W,
    KEY_E,
    KEY_R,
    KEY_T,
    KEY_Y,
    KEY_U,
    KEY_I,
    KEY_O,
    KEY_P,
    KEY_OPEN_BRACKET,
    KEY_CLOSED_BRACKET,
    KEY_ENTER,
    KEY_LEFT_CONTROL,
    KEY_A,
    KEY_S,
    KEY_D,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_SEMICOLON,
    KEY_SINGLE_QUOTE,
    KEY_BACK_TICK,
    KEY_LEFT_SHIFT,
    KEY_BACKSLASH,
    KEY_Z,
    KEY_X,
    KEY_C,
    KEY_V,
    KEY_B,
    KEY_N,
    KEY_M,
    KEY_COMMA,
    KEY_PERIOD,
    KEY_SLASH,
    KEY_RIGHT_SHIFT,
    KEY_KEYPAD_ASTERISK,
    KEY_LEFT_ALT,
    KEY_SPACE,
    KEY_CAPSLOCK,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_NUMBERLOCK,
    KEY_SCROLLLOCK,
    KEY_KEYPAD_7,
    KEY_KEYPAD_8,
    KEY_KEYPAD_9,
    KEY_KEYPAD_MINUS,
    KEY_KEYPAD_4,
    KEY_KEYPAD_5,
    KEY_KEYPAD_6,
    KEY_KEYPAD_PLUS,
    KEY_KEYPAD_1,
    KEY_KEYPAD_2,
    KEY_KEYPAD_3,
    KEY_KEYPAD_0,
    KEY_KEYPAD_PERIOD,
    KEY_F11,
    KEY_F12,
    
    KEY_PREVIOUS_TRACK,
    KEY_NEXT_TRACK,
    KEY_KEYPAD_ENTER,
    KEY_RIGHT_CONTROL,
    KEY_MUTE,
    KEY_CALCULATOR,
    KEY_PLAY,
    KEY_STOP,
    KEY_VOLUME_DOWN,
    KEY_VOLUME_UP,
    KEY_WWW_HOME,
    KEY_KEYPAD_SLASH,
    KEY_RIGHT_ALT,
    KEY_HOME,
    KEY_CURSOR_UP,
    KEY_PAGE_UP,
    KEY_CURSOR_LEFT,
    KEY_CURSOR_RIGHT,
    KEY_END,
    KEY_CURSOR_DOWN,
    KEY_PAGE_DOWN,
    KEY_INSERT,
    KEY_DELETE,
    KEY_LEFT_GUI,
    KEY_RIGHT_GUI,
    KEY_APPS,
    KEY_ACPI_POWER,
    KEY_ACPI_SLEEP,
    KEY_ACPI_WAKE,
    KEY_WWW_SEARCH,
    KEY_WWW_FAVORITES,
    KEY_WWW_REFRESH,
    KEY_WWW_STOP,
    KEY_WWW_FORWARD,
    KEY_WWW_BACK,
    KEY_MY_COMPUTER,
    KEY_EMAIL,
    KEY_MEDIA_SELECT,
    
    KEY_COUNT,
    // TODO: Add special keys
} key_t;

typedef struct kbd_ev_t
{
    key_action_t    action;
    key_t           keycode;
} kbd_ev_t;



