timeout: 25

wallpaper: boot():/boot/wallpaper.jpg
wallpaper_style: stretched

/kernel
    protocol: limine
    path: boot():/boot/kernel
    module_path: boot():/boot/kernel
    module_path: boot():/boot/initrd.tar
    
